# Stage 1: Build Angular application
FROM node:lts-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files to the working directory
COPY . .

# Expose the port that the app listens on
EXPOSE 4200

# Start the application
CMD ["npm", "start"]
